import Head from 'next/head'
import Wrapper from "@/components/wrapper";

import styles from '@/styles/Home.module.scss'

// import {} from '@next/font/google'


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Wrapper>
                    <div></div>
                </Wrapper>
            </main>
        </>
    )
}
